baseURL = 'https://gablaxian.com/'
languageCode = 'en-gb'
title = 'gablaxian.com'

[frontmatter]
  date = [':filename', ':default']

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"
